// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_from_uuid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserNameFromUUID = `-- name: GetUserNameFromUUID :one
SELECT name FROM users
WHERE id = $1
`

func (q *Queries) GetUserNameFromUUID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserNameFromUUID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
